name: Amy Costello
favicon: null
layout_spectrum: 0.3896274813450873
typography_spectrum: 0.0592023185454309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.28203520248644054
  lightness: 0.9847012916579843
  saturation: 0.1362733948044479
  rhythmicContrast: 0.056495326571166515
purpose: []
